package net.sppan.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOptions<M extends BaseOptions<M>> extends Model<M> implements IBean {

	public void setOptionKey(java.lang.String optionKey) {
		set("optionKey", optionKey);
	}

	public java.lang.String getOptionKey() {
		return get("optionKey");
	}

	public void setOptionValue(java.lang.String optionValue) {
		set("optionValue", optionValue);
	}

	public java.lang.String getOptionValue() {
		return get("optionValue");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

}
