package net.sppan.blog.model;

import net.sppan.blog.model.base.BaseBlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog> {
	private final User userDao = new User().dao();
	
	public User getAuthor(){
		return userDao.findById(getAuthorId());
	}
}
