package net.sppan.blog.model;

import net.sppan.blog.model.base.BaseOptions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Options extends BaseOptions<Options> {
	
}
