package net.sppan.blog.model;

import net.sppan.blog.model.base.BaseYoulian;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Youlian extends BaseYoulian<Youlian> {
	
}
