package net.sppan.jfinalblog.model;

import net.sppan.jfinalblog.model.base.BaseTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tag extends BaseTag<Tag> {
	
}
